export enum EnumPages {
  login = 'login',
  register = 'register',
  forgot_password = 'forgot-password',
  categories = 'categories',
  disputes = 'disputes',
  users = 'users',
  products = 'products',
  orders = 'orders',
  sales = 'sales',
  home = '',
  counts = 'counts',
  error = '**',
  store = 'store',
}
