export enum EnumPages {
  login = 'login',
  register = 'register',
  forgot_password = 'forgot-password',
  categories = 'categories',
  disputes = 'disputes',
  users = 'users',
  subcategories = 'subcategories',
  products = 'products',
  orders = 'orders',
  sales = 'sales',
  messages = 'messages',
  home = '',
  counts = 'counts',
  error = '**',
  stores = 'stores',
}
